POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Building a Node app from scratch",
    "author": "crmankin",
    "url": "https://fullstackopen.com/en/",
    "likes": 0
}